version: "3.1"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DATABASE=octo_events_app_development
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  db:
