default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: dbuser
  password: dbpass

development:
  <<: *default
  database: octo_events_app_development
  
test:
  <<: *default
  database: octo_events_app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
